{{- if .Values.imagePullSecrets }}
{{- $dockerconfig := "" }}
{{- range .Values.imagePullSecrets }}
  {{- if eq .name "dockerconfigjson" }}
    {{- $dockerconfig = .data }}
  {{- end }}
{{- end }}

{{- if $dockerconfig }}
apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  .dockerconfigjson: {{ $dockerconfig }}
type: kubernetes.io/dockerconfigjson
{{- end }}
{{- end }}