apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cinemaabyss-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: proxy-service
                port:
                  number: 8000
          
          - path: /events-service(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: events-service
                port:
                  number: 8082
          
          - path: /movies-service(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: movies-service
                port:
                  number: 8081
          
          - path: /monolith(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: monolith
                port:
                  number: 8080