apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewogICAgCSJnaGNyLmlvIjogewogICAgICAJCSJhdXRoIjogImRtNXBhMmxtYjNKdmRqcG5hWFJvZFdKZmNHRjBYekV4UVVKUU1rOWFTVEJCTXpKSWVFRjVVa1pHU1VkZlIyc3pZazVHTlZKc1owTkVkR0o2Y0RKSlNURldPV2hxV1cxRFZuZGlkM3BsYkhKQlQyNDJaMk5VZFZOTE56UXlSazR5UkUxR1dsWTFWams9IgogICAgCX0KICAgIH0sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKCSJjdXJyZW50Q29udGV4dCI6ICJkZXNrdG9wLWxpbnV4IiwKCSJwbHVnaW5zIjogewoJCSIteC1jbGktaGludHMiOiB7CgkJCSJlbmFibGVkIjogInRydWUiCgkJfQoJfSwKCSJmZWF0dXJlcyI6IHsKCQkiaG9va3MiOiAidHJ1ZSIKCX0KfQ==
type: kubernetes.io/dockerconfigjson
